Hr_System/urls.py
"""Hr_System URL Configuration"""

from django.conf import settings
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

"#importing views.py"
#from django.conf.urls import url 
from Hr_App import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', views.custom_login, name='logIn'),
    path('admin/', admin.site.urls),
    path('Discussions/', views.announcement_list, name='Discussions'),
    path('announcements/create/', views.create_announcement, name='create_announcement'),
    path('userProfile/', views.edit_user_profile, name='userProfile'),
    path('Employees/', views.employees_list, name='Employees'),
    path('Leaves/', views.leaves_view, name='Leaves'),
    path('Vaccincies/', views.all_job_openings, name='all_job_openings'),
    path('Vaccincies/', views.Vaccincies, name='Vaccincies'),
    path('Report/', views.Report, name='Report'),
    path('apply/', views.apply, name='apply'),
    path('apply/<int:opening_id>/', views.apply, name='apply_to_job'),
    path('ApplicationManagement/', views.applicant_list, name='applicant_list'),
    path('ApplicationManagement/', views.ApplicationManagement, name='ApplicationManagement'),
    path('addVacancy/', views.addVacancy, name='addVacancy'),
    path('delete_vacancy/<str:opening_id>/', views.delete_vacancy, name='delete_vacancy'),
    path('signup/', views.signup, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='logIn.html',
        success_url='/',  # Set the success URL to '/' (index page)
    ), name='login'),
    path('vaccan_no_log/', views.Vaccincies2, name='Vaccincies2'),
    path('logout/', views.logout_view, name='logout'),
    path('EvaluateApplicant/<int:applicant_id>/', views.EvaluateApplicant, name='EvaluateApplicant'),
    path('deleteApplicantJob/<int:applicantjob_id>/', views.delete_applicant_job, name='delete_applicant_job'),
    path('evaluate_employee/<int:employee_id>/', views.evaluate_employee, name='evaluate_employee'),
    path('employee_details/<int:employee_id>/', views.employee_details, name='employee_details'),
    path('applicant_details/<int:applicant_id>/', views.applicant_details, name='applicant_details'),
    path('download-employees/', views.download_employee_list, name='download_employees'),
    path('download-applicants/', views.download_applicant_list, name='download_applicants'),
    path('download-applicants/', views.download_applicant_list, name='download_applicants'),
    path('dashboard/employee/', views.employee_dashboard, name='employee_dashboard'),
    path('dashboard/applicant/', views.applicant_dashboard, name='applicant_dashboard'),
    path('evaluationreviews/<int:review_id>/', views.evaluationreview_detail, name='evaluationreview_detail'),
    path('evaluations/<int:review_id>/', views.PerformanceReview_detail, name='PerformanceReview_detail'),
    path('openings/<int:opening_id>/', views.opening_details, name='opening_details'),
    path('openings_no_log/<int:opening_id>/', views.opening_details_no_log, name='opening_details_no_log'),
    path('userProfile/edit/', views.edit_user_profile, name='edit_applicant_profile'),
    path('apply_for_leave/', views.apply_for_leave, name='apply_for_leave'),
    path('announcement/delete/<int:announcement_id>/', views.delete_announcement, name='delete_announcement'),
    path('approve_applicant_job/<int:applicantjob_id>/', views.approve_applicant_job, name='approve_applicant_job'),

]

Hr_App/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings


# Create your models here.
from django.db import models

# class User(models.Model):
#     id = models.AutoField(primary_key=True, max_length=255)
#     username=models.CharField(max_length=255)
#     password1=models.CharField(max_length=255)
#     password2= models.CharField(max_length=255)

class Jobs(models.Model):
    job_id = models.AutoField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255000)

    def __str__(self):
        return self.name 

class Locations(models.Model):
    location_id = models.AutoField(primary_key=True, max_length=255)
    country = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    governorate = models.CharField(max_length=255)

    def __str__(self):
        return self.country
    def __str__(self):
        return self.city

class Department(models.Model):
    department_id = models.AutoField(primary_key=True, max_length=255)
    department_name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.department_name  

class Employees(models.Model):
    employee_id = models.AutoField(primary_key=True, max_length=255)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    dob = models.DateField()
    email = models.EmailField(max_length = 254)
    join_date = models.DateField()
    mobile_number = models.DecimalField(max_digits=15, decimal_places=0)
    job = models.ForeignKey(Jobs, on_delete=models.CASCADE)
    location = models.ForeignKey(Locations, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=[('employee', 'Employee'), ('hr_admin', 'HR Admin')], default='employee')


    def __str__(self):
        return self.name




class Announcement(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='announcement_images/', null=True, blank=True)
    image_path = models.FileField(upload_to='announcement_images/', null=True, blank=True) 
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


    def __str__(self):
        return self.title


class PerformanceReview(models.Model):
    review_id = models.AutoField(primary_key=True)
    employee = models.ForeignKey('Employees', on_delete=models.CASCADE)
    reviewer = models.ForeignKey('Employees', related_name='reviewer', on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=5, decimal_places=2)
    review_date = models.DateField()
    comments = models.TextField()
    communication_skills = models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Satisfactory'), (3, 'Exemplary')])
    teamwork = models.IntegerField(choices=[(1, 'Requires Development'), (2, 'Effective'), (3, 'Highly Effective')])
    problem_solving = models.IntegerField(choices=[(1, 'Limited'), (2, 'Adequate'), (3, 'Resourceful')])
    adaptability = models.IntegerField(choices=[(1, 'Struggles to Adapt'), (2, 'Adapts Well'), (3, 'Quickly Adapts')])
    punctuality = models.IntegerField(choices=[(1, 'Often Late'), (2, 'Usually On Time'), (3, 'Consistently On Time')])
    leadership = models.IntegerField(choices=[(1, 'Occasionally Demonstrated'), (2, 'Frequently Demonstrated'), (3, 'Consistently Demonstrated')])
    # Other relevant fields as needed

    def __str__(self):
        return f"Performance Review for {self.employee} on {self.review_date}"


class EmployeePerformanceReview(models.Model):
    performance_review_id = models.AutoField(primary_key=True, max_length=255)
    review = models.ForeignKey(PerformanceReview, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)

    def __str__(self):
        return self.employee


class SalaryGrades(models.Model):
    grade_id = models.AutoField(primary_key=True, max_length=255)
    job = models.ForeignKey(Jobs, on_delete=models.CASCADE)
    salary_range = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.job

class Reports(models.Model):
    report_id = models.AutoField(primary_key=True, max_length=255)
    report_name = models.CharField(max_length=255)
    report_type = models.CharField(max_length=255)
    date = models.DateField()
    description = models.CharField(max_length=255)
    
    
    def __str__(self):
        return self.report_name

class Leaves(models.Model):
    leave_id = models.AutoField(primary_key=True, max_length=255)
    type = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.type

class EmployeeLeave(models.Model):
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)
    leave = models.ForeignKey(Leaves, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    reason = models.TextField()
    status = models.CharField(max_length=100, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')

    def __str__(self):
        return f"{self.employee.name} - {self.leave.type}"


class Applicants(models.Model):
    applicant_id = models.AutoField(primary_key=True, max_length=255)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    mobile_number = models.DecimalField(max_digits=15, decimal_places=0)
    dob = models.DateField()
    email = models.EmailField()
     
    def __str__(self):
        return self.name
class JobOpenings(models.Model):
    opening_id = models.AutoField(primary_key=True, max_length=255)
    job = models.ForeignKey(Jobs, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    date_posted = models.DateField()
    deadline = models.DateField()
    description = models.CharField( max_length=1000)

    @property
    def job_name(self):
        return self.job.name
    
    @property
    def job_description(self):
        return self.job.description

    @property
    def department_name(self):
        return self.department.department_name
    
    def __str__(self):
        return self.job    
class ApplicantJob(models.Model):
    applicantjob_id = models.AutoField(primary_key=True, max_length=255)
    applicant = models.ForeignKey(Applicants, on_delete=models.CASCADE, related_name='applied_jobs')
    opening = models.ForeignKey(JobOpenings, on_delete=models.CASCADE, related_name='applicants')
    application_date = models.DateField()
    status = models.CharField(max_length=255)
    reason_for_hire = models.CharField(max_length=255)
    cv = models.FileField(upload_to='cvs/', null=True, blank=True)

    def __str__(self):
        return str(self.applicant)

class EvaluationReview(models.Model):
    review_id = models.AutoField(primary_key=True, max_length=255)
    score = models.DecimalField(max_digits=10, decimal_places=2)
    review_date = models.DateField()
    applicant_id = models.ForeignKey(Applicants, on_delete=models.CASCADE)
    comments = models.CharField(max_length=255)
    communication_skills = models.IntegerField(choices=[(1, 'Poor'), (2, 'Good'), (3, 'Excellent')])
    facial_disclosure = models.IntegerField(choices=[(0, 'Hides expressions'), (1, 'Reveals expressions')])
    eye_contact = models.IntegerField(choices=[(0, 'Doesn’t keep eye contact'), (1, 'Normal')])
    posture = models.IntegerField(choices=[(0, 'Close'), (1, 'Open'), (2, 'Open all the time')])
    self_control = models.IntegerField(choices=[(0, 'Not maintained'), (1, 'Maintained')])
    personality = models.IntegerField(choices=[(1, 'Introvert'), (2, 'Ambivert'), (3, 'Extrovert')])
    handling_question_1 = models.IntegerField(choices=[(0, 'Poor'), (2, 'Good'), (3, 'Excellent')])
    handling_question_2 = models.IntegerField(choices=[(0, 'Poor'), (2, 'Good'), (3, 'Excellent')])
    applicant_job = models.ForeignKey(ApplicantJob, on_delete=models.CASCADE, related_name='evaluations', blank=True, null=True)

    def total_score(self):
        # Calculate total score based on all these fields
        total = sum([
            self.communication_skills,
            self.facial_disclosure,
            self.eye_contact,
            self.posture,
            self.self_control,
            self.personality,
            self.handling_question_1,
            self.handling_question_2,
            # ... add the rest of the handling question fields here ...
        ])
        return total

    def __str__(self):
        return f"Review for {self.applicant_id.name} on {self.review_date}"




    

class LeaveRecords(models.Model):
    record_id = models.AutoField(primary_key=True, max_length=255)
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)
    leave = models.ForeignKey(Leaves, on_delete=models.CASCADE)
    from_date = models.DateField()
    to_date = models.DateField()
    status = models.CharField(max_length=255)

    def __str__(self):
        return self.employee
    

templates/apply.html
{% load static %}
{% load my_custom_tags %}
<!doctype html>
<html class="no-js h-100" lang="en">
  <head>
    <!-- Google Tag Manager -->
    <script>dataLayer = [{ 'ga-tracking-id' : 'UA-115105611-1' }];</script>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-WGLBNC8');</script>
    <!-- End Google Tag Manager -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Add Vacancy</title>
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="styles/shards-dashboards.1.1.0.min.css">
    <link rel="stylesheet" href="styles/extras.1.1.0.min.css">
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.snow.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
  </head>

    <div class="container-fluid">
      <div class="row">
      
  <body class="h-100">
    <div class="container-fluid">
      <div class="row">
        <!-- Main Sidebar -->
        <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
          <div class="main-navbar">
            <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
              <a class="navbar-brand w-100 mr-0" href="#" style="line-height: 25px;">
                <div class="d-table m-auto">
                  <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 200px;"  src="{% static 'img/BP_logo.png' %}" alt="BP Logo">
                  <br>
                </div>
              </a>
              <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
              </a>
            </nav>
          </div>
          <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
            <div class="input-group input-group-seamless ml-3">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fas fa-search"></i>
                </div>
              </div>
              <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search">
            </div>
          </form>
          <div class="nav-wrapper">
            <ul class="nav flex-column">
              {% get_user_role request.user as user_role %}

              {% if user_role == 'applicant' %}
              <li class="nav-item">
                <a class="nav-link " href="{% url 'applicant_dashboard' %}">
                  <i class="material-icons">dashboard</i>
                  <span>Dashboard</span>
                </a>
              </li>
              {% endif %}

              {% if user_role == 'employee' %}
              <li class="nav-item">
                <a class="nav-link " href="{% url 'employee_dashboard' %}">
                  <i class="material-icons">dashboard</i>
                  <span>Dashboard</span>
                </a>
              </li>
              {% endif %}

              </li>
              {% if user_role == 'hr_admin' %}
              <li class="nav-item">
                <a class="nav-link " href="{% url 'index' %}">
                  <i class="material-icons">dashboard</i>
                  <span>Dashboard</span>
                </a>
              </li>
              {% endif %}

              {% if user_role == 'hr_admin' or user_role == 'employee' %}
              <li class="nav-item">
                <a class="nav-link " href="{% url 'Leaves' %}">
                  <i class="material-icons">directions_walk</i>
                  <span>Leaves</span>
                </a>
              </li>
             {% endif %}
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'Vaccincies' %}">
                  <i class="material-icons">business_center</i>
                  <span>Vacancies</span>
                </a>
              </li>
       
              
              {% if user_role == 'hr_admin' %}
              <li class="nav-item">
                <a class="nav-link " href="{% url 'ApplicationManagement' %}">
                  <i class="material-icons">recent_actors</i>
                  <span>Applicants</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'Employees' %}">
                  <i class="material-icons">wc</i>
                  <span>Employees</span>
                </a>
              </li>
              {% endif %}
             
              
              <li class="nav-item">
                <a class="nav-link " href="{% url 'Report' %}">
                  <i class="material-icons">content_paste</i>
                  <span>Report</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'Discussions' %}">
                  <i class="material-icons">question_answer</i>
                  <span>Announcements</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'userProfile' %}">
                  <i class="material-icons">person</i>
                  <span>User Profile</span>
                </a>
              </li>
            </ul>
          </div>
        </aside>
        <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
          <div class="main-navbar sticky-top bg-white">
            <!-- Main Navbar -->
            <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
              <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
                <div class="input-group input-group-seamless ml-3">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                     \
                    </div>
                  </div>
             
                </div>
              </form>
             
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle mr-2" style="height: 50px;" src="{% static 'img/user_avatar.png' %}" alt="User Avatar" >
                    {% if username %}
                     <span class="d-none d-md-inline-block">{{ username }}</span>
                    {% endif %}
                </a>
                  <div class="dropdown-menu dropdown-menu-small">
                   
                    <a class="dropdown-item text-danger" href="{% url 'logout' %}">
                      <i class="material-icons text-danger">&#xE879;</i> Logout </a>
                  </div>
                </li>
              </ul>
              <nav class="nav">
                <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                  <i class="material-icons">&#xE5D2;</i>
                </a>
              </nav>
            </nav>
          </div> <!-- / .main-navbar -->
          <div class="main-content-container container-fluid px-4">
            <!-- Page Header -->
            <div class="page-header row no-gutters py-4">
              <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Vacancies</span>
                <h3 class="page-title">Apply</h3>
              </div>
            </div>
            <!-- End Page Header -->
            <div class="row">
              <div class="col-lg-9 col-md-12">
                <div class="card card-small mb-3">
                    <!--add form -->
                    <div class="card-body">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

<div>
<label for="id_application_date">Application Date:</label>
<input type="text" class="form-control form-control-lg mb-3" type="date" name="application_date" id="id_application_date" value="{{ form.instance.application_date|date:'Y-m-d' }}" readonly>
{% if form.application_date.errors %}
<span class="error">{{ form.application_date.errors }}</span>
{% endif %}
</div>

<div>
<label for="id_reason_for_hire">Reason for Hire:</label>
<textarea name="reason_for_hire" class="form-control form-control-lg mb-3" id="id_reason_for_hire" cols="30" rows="5"></textarea>
{% if form.reason_for_hire.errors %}
<span class="error">{{ form.reason_for_hire.errors }}</span>
{% endif %}
</div>

<div>
<label for="id_cv">Upload CV:</label>
<input type="file" class="form-control form-control-lg mb-3" name="cv" id="id_cv">
{% if form.cv.errors %}
<span class="error">{{ form.cv.errors }}</span>
{% endif %}
</div>

<input type="submit" class="btn btn-accent" value="Apply">
</form>
                </div>
              </div>
               <!--end add form -->
                <!-- / Post Overview -->
              </div>
            </div>
          </div>
          <footer class="main-footer d-flex p-2 px-3 bg-white border-top">
            <span class="copyright ml-auto my-auto mr-2">Copyright © 2023 <a href="https://www.polytechnic.bh/" rel="nofollow">Bahrain Polytechnic</a></span>
          </footer>
        </main>
      </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
    <script src="scripts/extras.1.1.0.min.js"></script>
    <script src="scripts/shards-dashboards.1.1.0.min.js"></script>
    <script src="scripts/app/app-blog-overview.1.1.0.min.js"></script>
  </body>
</html>
<script>
   function getFormattedDate() {
  let today = new Date();
  let dd = String(today.getDate()).padStart(2, '0');
  let mm = String(today.getMonth() + 1).padStart(2, '0'); // January is 0!
  let yyyy = today.getFullYear();
  return yyyy + '-' + mm + '-' + dd;
}

// Set the value of the application_date input field to today's date when the DOM content is loaded
document.addEventListener('DOMContentLoaded', function() {
  document.getElementById('id_application_date').value = getFormattedDate();
});
</script>

  